### ISSUE TITLE
Add i18n support

### ISSUE THREAD

**Issue by kw214** [flame-engine/flame-docs-site#11]
Add i18n support.

**Comment by spydon** [comment]
> I plan to use my free time to translate documents

Many did for the readme too, it simply was too much organization so we decided to remove it, and it would be an even more massive undertaking for the docs.

The docs should always be updated in the same PR as the code is in to keep it up to date and this becomes impossible when we don't know all the languages that we would have the docs in, and then we have to make sure to know who to ping to update them and then after a while people don't want to maintain their translations and then we have to either find a replacement for them or remove the docs.
