### ISSUE TITLE
Unlist old versions from search engines

### ISSUE THREAD

**Issue by maurovanetti** [flame-engine/flame-docs-site#17]
When I google using queries like https://www.google.com/search?q=flame+SpriteComponent I always end up on old versions first.

Can we instruct the crawlers to ignore all versions but the latest, with a dynamically generated `robots.txt` or something?

**Comment by maurovanetti** [comment]
I see! It didn't work because it only deindexes the index.html file, but internal pages are still indexed because they don't contain the META tag.

`sed -i "/<head>/a  $no_index_string" docs/$version/index.html`

This commit was fine but it should be improved by including all files below the old versions' subtrees: https://github.com/flame-engine/flame-docs-site/pull/16/commits/3b0bfe450926fc713d50cd227cb1e78d50ba831f

**Comment by spydon** [comment]
Ah, that makes sense. Do you want to provide a PR? :)

**Comment by maurovanetti** [comment]
Not sure how this stuff works but let me try.

**Comment by maurovanetti** [comment]
BTW, my `robots.txt` suggestion was not a good idea. `noindex` is the way to go: https://developers.google.com/search/docs/crawling-indexing/robots/intro

**Comment by maurovanetti** [comment]
I checked: `noindex` is there now but the old pages are still listed. :-(
In some technical discussions online I found that it can take some time for Google to update their indexing, particularly if the website is not handled by its owners through the Google Search Console.
Let's check this again in a few weeks.

**Comment by spydon** [comment]
I think that we can ask for reindexing through the console, let me check with Luan

**Comment by spydon** [comment]
We requested a reindexing of the docs site now so hopefully it'll kick in soon.

**Comment by maurovanetti** [comment]
It looks good now!

**Comment by spydon** [comment]
> It looks good now!

Super! Thank you so much for this fix, it has been bugging us for years :sweat_smile:
