### ISSUE TITLE
Klondike Tutorial, Step 5: Add code and further explanation of FlatButton, or at least a link to its code

### ISSUE THREAD

**Issue by nickf2k** [flame-engine/flame-docs-site#19]
As I was following Klondike's instructions, near the end of step 5, I felt like the instructions writer was not as patient as in the previous steps. Many parts I found were not explained thoroughly, there is no code for FlatButton (I know there is code for it at the end, but there is no explanation about that).
I think we need to add some more detailed explanations, if there is no code for it then at least link to the code of those parts

**Comment by spydon** [comment]
Hi @nickf2k, this issue belongs in the Flame repository:
https://github.com/flame-engine/flame

**Comment by ufrshubham** [comment]
@nickf2k can you report this issue on the mono-repo linked in the readme of this repo?

**Comment by nickf2k** [comment]
@ufrshubham Sure. But I don't know the git link to this mono-repo. Can you tell me?

**Comment by nickf2k** [comment]
@ufrshubham i found it, thanks!
https://github.com/flame-engine/flame/blob/main/doc/tutorials/klondike/step5.md
